---
abstract: 'a collection of regular expressions for use with microblogging-style text (tweets, dents, microposts, etc.)'
author:
  - 'Gavin Carr <gavin@openfusion.com.au>'
  - 'Gavin Carr <gavin@openfusion.com.au>'
build_requires:
  Encode: 0
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common-microsyntax
no_index:
  directory:
    - inc
    - t
requires:
  Regexp::Common: 0
  utf8: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
